### ISSUE TITLE
throws ENOENT

### ISSUE THREAD

**Issue by Quramy** [reg-viz/reg-cli#93]
- reg-cli: version: `0.10.1`

When turning `-X client`, the following error is thrown:

```
Error: ENOENT: no such file or directory, open '/Users/yosuke/workspaces/javascript/reg-suit/node_modules/reg-cli/report/assets/cv-wasm_browser.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at createXimdiffWorker (/Users/yosuke/workspaces/javascript/reg-suit/node_modules/reg-cli/dist/report.js:92:35)
    at exports.default (/Users/yosuke/workspaces/javascript/reg-suit/node_modules/reg-cli/dist/report.js:104:22)
    at /Users/yosuke/workspaces/javascript/reg-suit/node_modules/reg-cli/dist/index.js:188:33
    at tryCatcher (/Users/yosuke/workspaces/javascript/reg-suit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/yosuke/workspaces/javascript/reg-suit/node_modules/bluebird/js/release/promise.js:512:31)
```

And the following is log of `node_modules/reg-cli/report/assets`:

```
node_modules/reg-cli/report/assets
├── favicon_failure.png
├── favicon_success.png
├── image.png
└── reglogo.svg

0 directories, 4 files
```

It seems that `cv-wasm_browser.js` and `cv-wasm_browser.wasm` are missing.

**Comment by bokuweb** [comment]
Fixed by https://github.com/reg-viz/reg-cli/pull/97
